language: php
php:
    - 7.0
    - 7.1
services:
    - memcached
    - mysql
before_install:
    echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
install:
    - composer install
before_script:
    - curl http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar -o php-cs-fixer.phar
    - chmod +x tests/mysql.sh && bash tests/mysql.sh
script:
    - php php-cs-fixer.phar fix -v --dry-run --diff src
    - "./vendor/bin/phpunit"
